name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/$GITHUB_REPOSITORY_OWNER/alpine_image
      TAG: ${{ github.run_id }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Log into GitHub Container Registry
      run: docker login ghcr.io -u $GITHUB_REPOSITORY_OWNER -p ${{ secrets.PAT }}
    
    - name: Build the Docker image
      run: docker build . -f sample-packages/docker/Dockerfile --tag $REGISTRY:$TAG
    
    - name: push image to GitHub Container Registry
      run: docker push $REGISTRY:$TAG


