name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . exercise-publish-package/sample-packages/docker/Dockerfile --tag alpine:latest
      
    - name: Log into GitHub Container Registry
      run: echo $GITHUB_TOKEN | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: push image to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/IMAGE_NAME:${{ github.run_id }}
        docker push $IMAGE_ID
